language: python
python: '3.8'
sudo: false
services:
  - postgresql
dist: xenial
install:
- pip install --upgrade pip wheel setuptools
- pip install virtualenv tox
before_script:
- sh -c "if [ '$DATABASE_ENGINE' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS
  gdpr_assist_tests;' -U postgres; fi"
- sh -c "if [ '$DATABASE_ENGINE' = 'pgsql' ]; then psql -c 'create database gdpr_assist_tests;'
  -U postgres; fi"
script:
- tox
env:
  matrix:
  - TOXENV=py38-django1.11 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
  - TOXENV=py38-django2.2 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
  - TOXENV=py38-django3.0 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
